# -*- coding: utf-8 -*-
"""90 questions de test reelles pour le chatbot FSBM : 30 FR + 30 EN + 30 Darija, 7 categories."""

# (categorie, langue, question, attendu_resume)
QUESTIONS = [
    # ─────────────── FRANCAIS (30) ───────────────
    ("Administration", "fr", "Comment s'inscrire a la FSBM ?", "Etapes preinscription preins.univh2c.ma"),
    ("Administration", "fr", "Quels documents faut-il pour la reinscription ?", "CIN, photos, recu"),
    ("Administration", "fr", "Comment obtenir une attestation de scolarite ?", "Service scolarite"),
    ("Administration", "fr", "Comment retirer mon diplome original ?", "Delai 6-12 mois, scolarite"),
    ("Administration", "fr", "Quel est le contact du service de scolarite ?", "Coordonnees scolarite"),
    ("Etudes", "fr", "Quelles sont les filieres de la FSBM ?", "Licences + masters"),
    ("Etudes", "fr", "Quelles licences propose le departement informatique ?", "DI, Full Stack, Cybersecurite..."),
    ("Etudes", "fr", "Qu'est-ce que la filiere Developpement Informatique ?", "Licence MI, full-stack"),
    ("Etudes", "fr", "Quels masters existent en informatique ?", "Masters MI"),
    ("Etudes", "fr", "Qui est responsable de la filiere Developpement Informatique ?", "Pr. SAEL Nihal"),
    ("Enseignants", "fr", "Combien de professeurs compte la FSBM ?", "239 enseignants-chercheurs"),
    ("Enseignants", "fr", "Quels sont les domaines de recherche du Pr. Benlahmer ?", "TALN, web semantique, ML"),
    ("Enseignants", "fr", "Qui dirige le departement de mathematiques et informatique ?", "Pr. ADNAOUI Khalid"),
    ("Enseignants", "fr", "Quels enseignants travaillent sur les chatbots ?", "Pr. Omar Zahour"),
    ("Enseignants", "fr", "Combien de citations a le Pr. Talea sur Google Scholar ?", "6755 citations"),
    ("Horaires", "fr", "Quand commencent les examens ?", "Hiver janvier, ete juin"),
    ("Horaires", "fr", "Ou trouver mon emploi du temps ?", "Site fsbm.ma, ENT"),
    ("Horaires", "fr", "Quand a lieu la session de rattrapage ?", "Septembre"),
    ("Horaires", "fr", "Comment se passe l'evaluation des modules ?", "CC + examen"),
    ("Horaires", "fr", "Quelles sont les dates des vacances universitaires ?", "Calendrier universitaire"),
    ("Orientation", "fr", "Comment obtenir une bourse ?", "ONOUSC, criteres"),
    ("Orientation", "fr", "Quelle filiere choisir apres le bac ?", "Conseil oriente"),
    ("Orientation", "fr", "Quels sont les debouches du Developpement Informatique ?", "Developpeur full-stack"),
    ("Orientation", "fr", "Comment faire un stage de fin d'etudes ?", "Convention, encadrant"),
    ("Orientation", "fr", "Peut-on continuer en master apres la licence ?", "Oui, selon admission"),
    ("General", "fr", "Qui est le doyen de la FSBM ?", "Pr. Abdeslam EL BOUARI"),
    ("General", "fr", "Combien de departements compte la FSBM ?", "6 departements"),
    ("General", "fr", "Ou se situe la FSBM ?", "Bd Driss El Harti, Ben M'Sik"),
    ("General", "fr", "Presente-moi la FSBM.", "Presentation institutionnelle"),
    ("General", "fr", "Quel est le site officiel de la faculte ?", "fsbm.ma"),

    # ─────────────── ANGLAIS (30) ───────────────
    ("Administration", "en", "How do I register at FSBM?", "Pre-registration steps"),
    ("Administration", "en", "What documents are needed for re-enrollment?", "ID, photos, receipt"),
    ("Administration", "en", "How can I get a school certificate?", "Registration office"),
    ("Administration", "en", "How do I collect my diploma?", "6-12 months, office"),
    ("Administration", "en", "What is the contact of the registration office?", "Scolarite contact"),
    ("Etudes", "en", "What programs does FSBM offer?", "Bachelors + masters"),
    ("Etudes", "en", "What bachelor degrees are available in computer science?", "DI, Full Stack..."),
    ("Etudes", "en", "What is the Software Development program about?", "Bachelor MI"),
    ("Etudes", "en", "Which master degrees exist in computer science?", "MI masters"),
    ("Etudes", "en", "Who is in charge of the Software Development program?", "Pr. SAEL Nihal"),
    ("Enseignants", "en", "How many professors are there at FSBM?", "239"),
    ("Enseignants", "en", "What are the research fields of Pr. Benlahmer?", "NLP, semantic web, ML"),
    ("Enseignants", "en", "Who heads the Mathematics and Computer Science department?", "Pr. ADNAOUI Khalid"),
    ("Enseignants", "en", "Which professors work on chatbots?", "Pr. Omar Zahour"),
    ("Enseignants", "en", "How many citations does Pr. Talea have?", "6755"),
    ("Horaires", "en", "When do exams start?", "January / June"),
    ("Horaires", "en", "Where can I find my timetable?", "fsbm.ma, ENT"),
    ("Horaires", "en", "When is the retake session?", "September"),
    ("Horaires", "en", "How are modules graded?", "Continuous + exam"),
    ("Horaires", "en", "When are the university holidays?", "Academic calendar"),
    ("Orientation", "en", "How do I get a scholarship?", "ONOUSC criteria"),
    ("Orientation", "en", "Which program should I choose after high school?", "Guidance"),
    ("Orientation", "en", "What are the career options in Software Development?", "Full-stack developer"),
    ("Orientation", "en", "How do I do my final-year internship?", "Agreement, supervisor"),
    ("Orientation", "en", "Can I continue to a master after the bachelor?", "Yes, on admission"),
    ("General", "en", "Who is the dean of FSBM?", "Pr. Abdeslam EL BOUARI"),
    ("General", "en", "How many departments does FSBM have?", "6"),
    ("General", "en", "Where is FSBM located?", "Ben M'Sik, Casablanca"),
    ("General", "en", "Tell me about FSBM.", "Institutional overview"),
    ("General", "en", "What is the official website of the faculty?", "fsbm.ma"),

    # ─────────────── DARIJA (30) ───────────────
    ("Administration", "darija", "Kifash ndir l'inscription f FSBM ?", "Tassjil preins.univh2c.ma"),
    ("Administration", "darija", "Achno mn watai9 khassni l reinscription ?", "Cin, photos"),
    ("Administration", "darija", "Kifash n7sel 3la attestation dyal scolarite ?", "Scolarite"),
    ("Administration", "darija", "Kifash nakhod diplome dyali ?", "Scolarite, delai"),
    ("Administration", "darija", "Achno houwa contact dyal scolarite ?", "Contact scolarite"),
    ("Etudes", "darija", "Achno hia les filieres f FSBM ?", "Licences o masters"),
    ("Etudes", "darija", "Achno mn licence kayna f l'informatique ?", "DI, Full Stack..."),
    ("Etudes", "darija", "Achno hia filiere Developpement Informatique ?", "Licence MI"),
    ("Etudes", "darija", "Wach kayn master f l'informatique ?", "Masters MI"),
    ("Etudes", "darija", "Chkoun mas'oul 3la filiere DI ?", "Pr. SAEL Nihal"),
    ("Enseignants", "darija", "Ch7al mn ustad kayn f FSBM ?", "239"),
    ("Enseignants", "darija", "Achno houwa l majal dyal recherche dyal Pr. Benlahmer ?", "TALN, web semantique"),
    ("Enseignants", "darija", "Chkoun li kaydir departement dyal mathematiques o informatique ?", "Pr. ADNAOUI Khalid"),
    ("Enseignants", "darija", "Chkoun mn ustad khddam 3la les chatbots ?", "Pr. Omar Zahour"),
    ("Enseignants", "darija", "Ch7al mn citation 3and Pr. Talea f Google Scholar ?", "6755"),
    ("Horaires", "darija", "Imta kaybdaw lexamens ?", "Janvier / juin"),
    ("Horaires", "darija", "Fin n9dr nl9a emploi du temps dyali ?", "fsbm.ma, ENT"),
    ("Horaires", "darija", "Imta kayna session dyal rattrapage ?", "Septembre"),
    ("Horaires", "darija", "Kifash katdoz l'evaluation dyal les modules ?", "CC + examen"),
    ("Horaires", "darija", "Imta kayna l3otla dyal jami3a ?", "Calendrier"),
    ("Orientation", "darija", "Kifash n7sel 3la bourse ?", "ONOUSC"),
    ("Orientation", "darija", "Ina filiere khassni nakhtar mn ba3d bac ?", "Conseil"),
    ("Orientation", "darija", "Achno houma les debouches dyal Developpement Informatique ?", "Developpeur"),
    ("Orientation", "darija", "Kifash ndir stage dyal fin d'etudes ?", "Convention"),
    ("Orientation", "darija", "Wach n9dr nkml master mn ba3d licence ?", "Iyeh"),
    ("General", "darija", "Chkoun houwa l3amid dyal FSBM ?", "Pr. Abdeslam EL BOUARI"),
    ("General", "darija", "Ch7al mn departement kayn f FSBM ?", "6"),
    ("General", "darija", "Fin kayna FSBM ?", "Ben M'Sik, Casablanca"),
    ("General", "darija", "3awnni, 9ddemli FSBM.", "Presentation"),
    ("General", "darija", "Achno houwa site rasmi dyal lkouliya ?", "fsbm.ma"),
]

assert len(QUESTIONS) == 90, len(QUESTIONS)
